// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: product.proto

package productpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestProductGet struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          *RequestProductCreateData `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestProductGet) Reset() {
	*x = RequestProductGet{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProductGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProductGet) ProtoMessage() {}

func (x *RequestProductGet) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProductGet.ProtoReflect.Descriptor instead.
func (*RequestProductGet) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *RequestProductGet) GetData() *RequestProductCreateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RequestProductCreateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestProductCreateData) Reset() {
	*x = RequestProductCreateData{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProductCreateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProductCreateData) ProtoMessage() {}

func (x *RequestProductCreateData) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProductCreateData.ProtoReflect.Descriptor instead.
func (*RequestProductCreateData) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *RequestProductCreateData) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ResponseProductGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseProductGet) Reset() {
	*x = ResponseProductGet{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseProductGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseProductGet) ProtoMessage() {}

func (x *ResponseProductGet) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseProductGet.ProtoReflect.Descriptor instead.
func (*ResponseProductGet) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseProductGet) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\"J\n" +
	"\x11RequestProductGet\x125\n" +
	"\x04Data\x18\x01 \x01(\v2!.product.RequestProductCreateDataR\x04Data\"*\n" +
	"\x18RequestProductCreateData\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\"(\n" +
	"\x12ResponseProductGet\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x05R\x04Code2P\n" +
	"\aProduct\x12E\n" +
	"\n" +
	"GetProduct\x12\x1a.product.RequestProductGet\x1a\x1b.product.ResponseProductGetBFZDgithub.com/ChanKachan/business-card-product/pb/cardProduct;productpbb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_product_proto_goTypes = []any{
	(*RequestProductGet)(nil),        // 0: product.RequestProductGet
	(*RequestProductCreateData)(nil), // 1: product.RequestProductCreateData
	(*ResponseProductGet)(nil),       // 2: product.ResponseProductGet
}
var file_product_proto_depIdxs = []int32{
	1, // 0: product.RequestProductGet.Data:type_name -> product.RequestProductCreateData
	0, // 1: product.Product.GetProduct:input_type -> product.RequestProductGet
	2, // 2: product.Product.GetProduct:output_type -> product.ResponseProductGet
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
